appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: rN31K0DyU92MSUiwwb0nEuARvNXGyzWsV8cO6e1YPZGizjU8It08t9WNR2TCcvWm12xt7wiRHUqRT4qJXavSyzVePSo9SzQ6DePfkJsQaOxKNJsNbRzrv8jaFybNc1e52e3KJmAFFxhcOWzcIFDkxJpz75aO8tIq68t3FHynCNmE4laWPvN8Dv8J/g9kbWfOpHwabZXEbZeL2m4sqTWzzbjvblzk5G49mLbZQhY+vUL2GWtnB2GAwP5LsDcKf2EjsWujMl9Q23hP+DWhUYLLqJU0upa9YnhiRFIUIgAyxM7U1gHNHW63tM0ikLWsT2j26Tg72T9xvgLt9Pj3Gz+mU+i9h1Y9sMkeqOpirLx3SGOECoYG4x+Qocax65YeEfjKbGzMKHaqUaaHt840eQispMzdmOuXU6QYYZ79/y4F2X2NZycjcGgHqPYwkUUv76GuoU/SD5e21uVaEwARawRndRLJmNZSMrrKr6kIWUC26CUTMcXazsbRi5YhUVZmX2OQiz5u7ExFhk/UHKlQjwxm5CLEBo9qQ5oW1hOkbRyABbKAjpIS78hEJgHbitJHj7nSGitSEg1euq9Zov6gC8iVAVYutylpEi/g42+3m+NKjY4CtB/I9iZVk82HJKTWfWEBf8/OkB9pLqyvfItCe6ERGBaf37HvzU0kMCMlt7LatGw=
conda_forge_output_validation: true
