travis:
  secure:
    BINSTAR_TOKEN: O00bCAqbvw7QzC7Aj74iKRCBCh+jPdIwGRHaaFU6/n7un5LUiJtkv99yW11ecwWZgTiZmkkmG6/eIbx8oO+NZ28q2ipKqhEzMW0qKWyJ/WCajaSGPB43C3VQGV05LmgL+KJ82aWIPENxSaZfPfVXSpCRB5c+33xFTAg0PkhrUh4y4SJX23iRowGC98y991jd/ZcbFdQit94ZtSZkYwC80BdJWw6r2ExO53jaR8SaDYkg6gxdB+pJbhdnp5I3c9/P4l8LqT5G3XYtgj66JUOc7N2Fr+jxnw0MQcH9BDs5uqIoUOYUlc+DhJ+lTGu135VMfpXFhFxs9TFJ8XgxJzBWKznT1lSzDN1WzLmoz30wwuVsT/6+/lLw6kDk8CvajRVoENhN14lEUopXzpVRWBUiNy40xuGaGnzLmN59beKNFgyj9z2Y/ZKp0YsKO/xUiBto7h0JFNgbOeqLBzIX+/780EepEZ9Emk468uMyW8rg17YXApFa9/lXfa3XC+4XXSVontCKzj5klq7AZOofcEBHIR76gin4MeIX2/z2v/KRG476MPZqnKazjbpCmUz9OtPA2xDVM6FPaqQLPXKqyu/eAR/hVylBdkVlUDu6Erk84ZKtCR8NvDY2All32KI7mqjnrN6APm37uHmMcarFI9ZfQ2aoDTZKqC19ZqjAjTnsYDs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
