travis:
  secure:
    BINSTAR_TOKEN: MTYC28Cv5vSxT5gwprjxPcOnS4vP23DwG4Q7h5hoO452VPyEKBfYUvwv2HGjgHXlPVpd+Sl48lf9IF49O1wcxHfKlOO1MinV7xUnClg3LMhXZCPcZoAXR5K4Qv8Ek9oOmontpJXte+SgdFWarM29q5WjJm/1vTzpiSNyusOm910xDXzX7yWufCEHHXzAJb8SJy56qwBuM8xwANe4YJ0AGTYq33UnxzPswDi3eG1kZaBV6MaE0EadWnDPejaNVRBinfKGWF8425aFozbMmp83B3zDrCNNKcAoC/ftrEMMqSUFqPU8cUTI5ff03FsGDopERtNW1U5y7hEXDAMtxWDRVmA84sT0hfGFLRTWWKpgVRRkjMGggiJJlnNWtCInZMTw4b6JX+9/YnSQXSYlfB+RcsbsN9g4z0HPYZFG5Vfjc5ML3EKnrUglwfdEquw4GZGdl8ptlgGQ2RJSqNHD6kFZd4KgUMaeIQWi081FdblNxR+sLAqerkI78Ml/7bOcQZhMgwoIs0zgDTZIJi7xdMkmGfR+OFMqHYdCMg9PQCH8LiLfn3/rtCWQwFLhu6hH+HK/kcesCfZyEbUkgJ7dzCcyWCB83IXnDxjWYENsTPPsvn02bh/BhXKdv9jFjpXWok/0EtuHvE0CPIQjsrzGZ34+wwOtYc1MIVbsyR8uhDz7D4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
