travis:
  secure:
    BINSTAR_TOKEN: Tn753hKCPP0EMsVTiIiJDtgfiEvD7yHD/YFlHGWeuDcpUDqwuyh9nbr7V3ypnDSdlBR1B9xX2No1SQen3hAFc0IclMRcBnCw7QiPKxX808tWMihUUH34OarjW0vINZVZSUmlU1UDjpOqwu8YG96Vqrwvp9YYX+eAyeQq7AXyY5XeYTjUKgcnDV+hcL0qpqx+M1JrkZSfZ19eR9xskA6jg9ZwRZfI6EHRFdqjC6V6EqcrbgZZ3cCt2ajWvfzTlMDJvKh/NLtOA60uOMt5QhHMzyaSBVO+08qqnqvErJc+Ovhugv/0ttVeKXtphS78NWOPk3WQmmhOFt/oWQULP9JymvjJX3rgHdOBf6WWbN4DeGYJQ+yDuGV1XYRShOZM9aaJT42Hb77r1CvB7zbNcwyjmI4n6SbPUKb3aZ6KoRRTaWkFiPPZxS8102358rVCeb3QL8ee1ZLFPCXmtEexCA+IJFi2AYU0cldvlwsds9+6Bs2JZXiA4I0sylbyMHWi2d0jhVYI6j/2DixsT6lJJz2dwEG633zmS5FAHFKqQe1hgPigzD2f02885CEtewGgf8pT2O8Jdnq8NGWDSXg7WOOszf3mjYKq/lcpYl+dyZXv+B63nrOxzqF+X+35H+Exnc6sRClU35oFvoornYbKTj9eevDPU/3YktbZfGbiihzEnNU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
